version: "3.7"

services:
  dev:
    container_name: <bootstrap-node-project>
    build:
      context: .
      dockerfile: Dockerfile.dev
    tty: true
    volumes:
      - .:/var/development/workspace:cached

  database:
    image: mysql:5.7

    environment:
      MYSQL_DATABASE: <bootstrap-node-project-database>
      MYSQL_USER: <user>
      MYSQL_ROOT_PASSWORD: <password>

    ports:
      - "3307:3306"
